<font color="green">To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.</font>

# Python Programming:  Simple Random Sampling


## Importing our Libraries

In [1]:
# importing numpy
import numpy as np

# importing pandas
import pandas as pd

# importing random module
# we will use random.sample() function to return a k length 
# list of unique elements chosen from our population
import random

## 1.0 Selecting More than One item from a List

In [6]:
# Example 1
# ---
# Selecting more than one item from a list 

list = [20, 40, 80, 100, 120]
print ("Choosing 3 random items from a list using sample function", random.sample(list, k=3))

list = [20, 40, 20, 20, 20]
print ("Choosing 3 random items from a list using sample function",random.sample(list, k=3))

# As you can see we pass k=3 to choose 3 random elements from a list. 
# In return, we got a list of 3 random items.

Choosing 3 random items from a list using sample function [120, 100, 20]
Choosing 3 random items from a list using sample function [20, 40, 20]


### <font color="green"> 1.0 Challenges</font>

In [11]:
# Challenge 1
# ---
# Question: Create a list containing 10 counties in Kenya 
# then select 2 random counties from the list.
listn = ['nakuru', 'nairobi', 'kisumu', 'mombasa','narok','makueni','kitui','machakos','kilifi','kwale']
print ("Choosing 3 random items from a list using sample function", random.sample(listn, k=3))

Choosing 3 random items from a list using sample function ['machakos', 'kisumu', 'mombasa']


## 2.0  Selecting the Random Sample from Dictionary

In [12]:
# Example 1
# ---
# We can select a random key-value pair from the dictionary as shown 
# ---
#
marks_dict = {
  "Kelly": 55,
  "jhon": 70,
  "Donald": 60,
  "Lennin" :50
}

print ("Choosing 2 random items from a dictionary using sample method ", random.sample(marks_dict.items(), k=2))

Choosing 2 random items from a dictionary using sample method  [('jhon', 70), ('Lennin', 50)]


### <font color="green">2.0 Challenges</font>

In [13]:
# Challenge 1
# ---
# A caterer offers three different food packages; 
# bronze package: starch:rice stew:chicken curry vegetable:cabbages desert:melon
# silver package: starch:rice and chappati  stew:beef curry vegetable:spinach desert:melon and bananas
# gold package: starch:rice, chappati and mukimo stew: beef curry vegetable:spinach and managu desert: tart
# Create a dictionary that stores the above information and select a sample of size 2 
# ---
package_dict = {
  "bronze package": 'starch:rice stew:chicken curry vegetable:cabbages desert:melon',
  "silver package": 'starch:rice and chappati  stew:beef curry vegetable:spinach desert:melon and bananas',
  "gold package": 'starch:rice, chappati and mukimo stew: beef curry vegetable:spinach and managu desert: tart',
}
print ("Choosing 2 random items from a dictionary using sample method ", random.sample(package_dict.items(), k=2))

Choosing 2 random items from a dictionary using sample method  [('gold package', 'starch:rice, chappati and mukimo stew: beef curry vegetable:spinach and managu desert: tart'), ('silver package', 'starch:rice and chappati  stew:beef curry vegetable:spinach desert:melon and bananas')]


## 3.0 Selecting a Random Sample with Replacement to including repetition


In [20]:
# Example 1
# ---
# We can select a random sample with replacement to include repetition as shown below
# ---
# 
names = ["Roger", "Nadal", "Novac", "Andre", "Sarena", "Mariya", "Martina"]

print("random sample with replacement to including repetition ", random.choices(names, k=3))

random sample with replacement to including repetition  ['Sarena', 'Andre', 'Sarena']


### <font color="green">3.0 Challenges</font>

In [21]:
# Challenge 1
# ---
# Question: Select a random sample of 3 with replacement to include replacement from the 
# following list of months
# ---
#

months = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
          'August', 'September', 'October', 'November', 'December']

print("random sample with replacement to including repetition ", random.choices(months, k=3))

random sample with replacement to including repetition  ['June', 'March', 'July']


## 4.0 Selecting a Random Sample from a Range of Integers

In [22]:
# Example 1
# ---
# We can select a random sample from a range of integers as shown below
# ---
# 

weight_set = {40, 50, 55, 65, 75, 80}

print ("Choosing 4 random items from a set ", random.sample(weight_set, k=4))

Choosing 4 random items from a set  [50, 75, 55, 80]


### <font color="green">4.1 Challenges</font>

In [23]:
# Challenge 1
# ---
# Question: Select a random sample from a range of integers as shown below
# --- 
# 
weight_set = {4, 5, 6, 7, 8, 9, 10}

print ("Choosing 4 random items from a set ", random.sample(weight_set, k=4))

Choosing 4 random items from a set  [4, 7, 9, 8]


## 5.0 Selecting a Sample Array from a Large multidimensional Array



In [24]:
# Example 1
# ---
# We can select a sample array from a large multidimensional array as shown
# ---
# 

array = np.array([[2 ,4, 6], [5, 10, 15], [6, 12, 18], [7, 14, 21], [8, 16, 24]]) 
print("Printing 2D Array")
print(array)

# selecting multiple random rows from the 2D as shown
print("Selecting multiple random rows from the 2D array")
randomRows = np.random.randint(5, size=2)
for i in randomRows:
  print(array[i,:])

Printing 2D Array
[[ 2  4  6]
 [ 5 10 15]
 [ 6 12 18]
 [ 7 14 21]
 [ 8 16 24]]
Selecting multiple random rows from the 2D array
[ 6 12 18]
[ 7 14 21]


### <font color="green">5.0 Challenges</font>

In [26]:
# Challenge 1
# ---
# Question: Select two arrays from the given multidimensional array
# ---
# 

a = [[2, 4, 6, 8, 10], [3, 6, 9, 12, 15], [4, 8, 12, 16, 20], [1 ,2 , 4, 5, 6], [5, 10, 15, 20, 25], [6, 12, 18, 24, 30], [7, 14, 21, 28, 35]]  
array = np.array(a) 
print("Printing 2D Array")
print(array)

# selecting multiple random rows from the 2D as shown
print("Selecting multiple random rows from the 2D array")
randomRows = np.random.randint(5, size=2)
for i in randomRows:
  print(array[i,:])


Printing 2D Array
[[ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 1  2  4  5  6]
 [ 5 10 15 20 25]
 [ 6 12 18 24 30]
 [ 7 14 21 28 35]]
Selecting multiple random rows from the 2D array
[ 2  4  6  8 10]
[ 4  8 12 16 20]


## 6.0 Selecting Random Samples from a Dataset

In [29]:
# Example 1
# ---
# Selecting a random sample from the following medical appointments dataset
# ---
# Dataset url = http://bit.ly/MedicalAppointmentsDataset
# ---
# 

# Loading the dataset
medical_df = pd.read_csv("http://bit.ly/MedicalAppointmentsDataset")

# Determining the size
print(medical_df.shape)


# Previewing the dataset
print(medical_df.head())

# Selecting the sample 
medical_sample = medical_df.sample(n = 10, replace="False")
print(medical_sample)

(110527, 14)
      PatientId  AppointmentID Gender          ScheduledDay  \
0  2.987250e+13        5642903      F  2016-04-29T18:38:08Z   
1  5.589978e+14        5642503      M  2016-04-29T16:08:27Z   
2  4.262962e+12        5642549      F  2016-04-29T16:19:04Z   
3  8.679512e+11        5642828      F  2016-04-29T17:29:31Z   
4  8.841186e+12        5642494      F  2016-04-29T16:07:23Z   

         AppointmentDay  Age      Neighbourhood  Scholarship  Hipertension  \
0  2016-04-29T00:00:00Z   62    JARDIM DA PENHA            0             1   
1  2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0             0   
2  2016-04-29T00:00:00Z   62      MATA DA PRAIA            0             0   
3  2016-04-29T00:00:00Z    8  PONTAL DE CAMBURI            0             0   
4  2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0             1   

   Diabetes  Alcoholism  Handcap  SMS_received No-show  
0         0           0        0             0      No  
1         0           0  

### <font color="green">6.0 Challenges </font>

In [30]:
# Challenge 1
# ---
# Select a random sample of 10 from the given dataset below 
# ---
# Dataset url = http://bit.ly/DSRussianInvestigation
# ---
#
# Loading the dataset
df = pd.read_csv("http://bit.ly/DSRussianInvestigation")

# Determining the size
print(df.shape)


# Previewing the dataset
print(df.head())

# Selecting the sample 
df_sample = df.sample(n = 10, replace="False")
print(df_sample)

(194, 13)
  investigation investigation-start investigation-end  investigation-days  \
0     watergate          1973-05-19        1977-06-19                1492   
1     watergate          1973-05-19        1977-06-19                1492   
2     watergate          1973-05-19        1977-06-19                1492   
3     watergate          1973-05-19        1977-06-19                1492   
4     watergate          1973-05-19        1977-06-19                1492   

                  name  indictment-days          type     cp-date  cp-days  \
0      James W. McCord            -246.0   conviction  1973-01-30   -109.0   
1    Bernard L. Barker            -246.0   conviction  1973-01-15   -124.0   
2    Bernard L. Barker             292.0   conviction  1974-07-12    419.0   
3  Eugenio R. Martinez            -246.0  guilty-plea  1973-01-15   -124.0   
4  Eugenio R. Martinez             292.0   conviction  1974-07-12    419.0   

   overturned  pardoned  american      president  
0      

In [36]:
# Challenge 2
# ---
# A medical company would like to follow up with 50 patients who never showed up for appointments 
# but received an sms. Select a random sample from such patients given the medical dataset below 
# ---
# Dataset 
url = "http://bit.ly/MedicalAppointmentsDataset"
df = pd.read_csv(url)
print(df.shape)

#Filter the patients who received the sms
df = df[df['SMS_received'] ==1]

# Selecting the sample 
df_sample = df.sample(n = 50, replace="False")
print(df_sample)

(110527, 14)
           PatientId  AppointmentID Gender          ScheduledDay  \
5732    1.335689e+10        5731923      F  2016-05-24T10:43:21Z   
75348   2.415580e+10        5680399      F  2016-05-10T11:51:18Z   
29007   5.246374e+12        5596591      F  2016-04-18T14:55:06Z   
91875   5.574136e+13        5733043      F  2016-05-24T13:13:58Z   
84166   1.681732e+14        5713913      F  2016-05-18T10:56:28Z   
44115   5.822789e+14        5593946      F  2016-04-18T10:02:11Z   
58631   5.984720e+14        5571114      M  2016-04-12T08:41:36Z   
85927   3.968440e+11        5578508      M  2016-04-13T12:39:21Z   
100679  2.655612e+13        5608964      M  2016-04-20T14:52:08Z   
98209   4.575618e+14        5707538      M  2016-05-17T09:45:22Z   
46507   6.417624e+13        5589896      F  2016-04-15T13:06:22Z   
15673   3.666592e+13        5714766      F  2016-05-18T13:03:27Z   
59051   9.179366e+11        5543400      F  2016-04-05T10:06:43Z   
19475   3.677784e+13        5630581