<font color="green">*To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.*</font>

# Python Programming: Hyperparameter Tuning

## Example 

In [32]:
# Loading libraries
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
from sklearn import linear_model, datasets
from sklearn.model_selection import GridSearchCV

In [33]:
# Loading data
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [37]:
# Creating the logistic regression
logistic = linear_model.LogisticRegression(solver='lbfgs')

In [38]:
# Creating regularization penalty space
penalty = ['l1', 'l2']

# Creating regularization hyperparameter space
C = np.logspace(0, 4, 10)

# Creating hyperparameter options
hyperparameters = dict(C=C, penalty=penalty)

In [39]:
# Creating grid search using 5-fold cross validation
clf = GridSearchCV(logistic, hyperparameters, cv=5, verbose=0)

In [40]:
# Fitting grid search
best_model = clf.fit(X, y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


In [9]:
# Viewing best hyperparameters
print('Best Penalty:', best_model.best_estimator_.get_params()['penalty'])
print('Best C:', best_model.best_estimator_.get_params()['C'])

Best Penalty: l2
Best C: 7.742636826811269


In [10]:
# Predicting target vector
best_model.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## <font color="green">Challenge 1</font>

In [17]:
# Challenge 1
# ---
# Create a linear logistic regression model to predict the gender. 
# Perform hyperparameter tuning as well. 
# ---
# Dataset 

url = 'http://bit.ly/HeightsWeightsDataset'
df =pd.read_csv(url)
df.head()


Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [18]:
# Understanding the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  10000 non-null  object 
 1   Height  10000 non-null  float64
 2   Weight  10000 non-null  float64
dtypes: float64(2), object(1)
memory usage: 234.5+ KB


In [19]:
# Understanding Gender colum
df.Gender.unique()

array(['Male', 'Female'], dtype=object)

In [20]:
# Label encoding Gender columns to Binomial for our logistic model
df = df.replace({"Gender":{"Male":1,"Female":0}})
df.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [21]:
# Splitting our dataset

X = df.drop("Gender",axis=1)
y = df["Gender"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

In [ ]:
# Creating the logistic regression
logistic = linear_model.LogisticRegression()

# Creating regularization penalty space
penalty = ['l1', 'l2']

# Creating regularization hyperparameter space
C = np.logspace(0, 4, 10)

# Creating hyperparameter options
hyperparameters = dict(C=C, penalty=penalty)

# Creating grid search using 5-fold cross validation
clf = GridSearchCV(logistic, hyperparameters, cv=5, verbose=0)

In [22]:
# Training/Fitting grid search
best_model = clf.fit(X, y)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
50 fits failed out of a total of 100.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py", line 449, in _check_solver
    % (solver, penalty)
ValueError: Solve

In [23]:
# Using our model to make a prediction
#
y_pred = best_model.predict(X_test)

array([0, 1, 1, ..., 0, 1, 1])

In [24]:
# comparing the test and predicted
comparison_frame = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
comparison_frame.head(10)

Actual  Predicted
9394       0          0
898        1          1
2398       1          1
5906       0          0
2343       1          1
8225       0          0
5506       0          0
6451       0          0
2670       1          1
3497       1          1

In [25]:
# describe
comparison_frame.describe()

Actual    Predicted
count  2000.000000  2000.000000
mean      0.494000     0.492000
std       0.500089     0.500061
min       0.000000     0.000000
25%       0.000000     0.000000
50%       0.000000     0.000000
75%       1.000000     1.000000
max       1.000000     1.000000

In [26]:
# Evaluating the model
#
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' , accuracy_score(y_test, y_pred))
# The results from the confusion matrix tell us that 1846 out of 2000 are the number of correct predictions. 
# Accuracy score is 92.3%

[[937  75]
 [ 79 909]]
Accuracy 0.923


In [31]:
from sklearn import metrics

# Our first metric is MAE - Mean absolute error
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))

# We can also use MSE - Mean squared error
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  

# Finally, the most popular metric: RMSE - Root mean squared error
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

mean = df["Gender"].mean()
print(mean)
rmse = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
x = 0.1*mean
if rmse >x:
  print("The model/algorithm is not Accurate")
else:
  print("The model/algorithm is Accurate")

Mean Absolute Error: 0.077
Mean Squared Error: 0.077
Root Mean Squared Error: 0.27748873851023215
0.5
The model/algorithm is not Accurate


## <font color="green">Challenge 2</font>

In [ ]:
# Challenge 2
# ---
# Use the breast cancer dataset to create a logistic regression machine learning model.
# To improve the accuracy of the model, perform hyperparameter tuning.
# ---
# Dataset 
source = 'https://bit.ly/breast_cancer_dataset1'


## <font color="green">Challenge 3</font>

In [ ]:
# Challenge 3
# ---
# Build a regression model to determine whether a patient has diabetes or not.
# To improve the accuracy of the model, perform hyperparameter tuning.
# ---
# Dataset source = https://bit.ly/Diabetes_dataset
# ---
#
OUR CODE GOES HERE

## <font color="green">Challenge 4</font>

In [ ]:
# Challenge 4
# ---
# Build a model to determine whether a patient will be admitted. 
# To improve the accuracy of the model, perform hyperparameter tuning.
# ---
# Dataset url = https://bit.ly/patientAdmissionDataset
# ---
# 
OUR CODE GOES HERE

## <font color="green">Challenge 5</font>

In [ ]:
# Challenge 5
# ---
# You have a telecom firm which has collected data of all its customers. 
# The main types of attributes are: 
# 1.Demographics (age, gender etc.) 
# 2.Services availed (internet packs purchased, special offers etc) 
# 3.Expenses (amount of recharge done per month etc.) 
# Based on all this past information, build an accurate model which will predict 
# whether a particular customer will churn or not. 
# ---
# Dataset source = https://bit.ly/churnPredictDataset
# ---
# 
OUR CODE GOES HERE